env:
  global:
    - CRATE_NAME=bit_reverse

language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo test --verbose
  - cargo test --verbose --no-default-features
  - cargo doc --no-deps
